### ISSUE TITLE
about MUX conv parameter scales

### ISSUE THREAD

**Issue by rangmiao** [human-analysis/MUXConv#1]
hello,when I see this code,I have a problem. in the class of MuxInvertedResidual ,here is a parameter "scales", default 0,and if you want to use mux conv,this parameter must be a list.  in MUXNet, this "scales" is always  0，that is to say, MUXNet is  not used MUXcov?

**Comment by mikelzc1990** [comment]
There are two parts in MUXConv: 1) spatial mux (``scales`` parameter you mentioned); and 2) channel mux (``split_ratio`` parameter).  What we observe from our ablation study (Fig. 8a in the paper) is that the spatial mux is beneficial at very low FLOPs regime. Given the latency overhead, I remove the spatial mux operation in m/l models, with ~0.1% loss in ImageNet Top-1 accuracy. We will release the xs and s models very soon and both of them use spatial mux.

**Comment by rangmiao** [comment]
thanks
